services:
  - type: web
    name: syracuse-pitch
    env: node
    plan: free
    buildCommand: npm install && npm run install:all && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
